FROM node:20-alpine as builder_fe

WORKDIR /app

RUN npm install -g pnpm 

COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml

RUN pnpm install 

COPY . .

RUN pnpm run build 
## bs , hume ab html css js files mil chuki hain 

FROM nginx:alpine 

COPY --from=builder_fe /app/dist /usr/share/nginx/html 

EXPOSE 80 

CMD [ "nginx" , "-g" , "daemon off;" ]