FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm 

COPY package.json package.json 
COPY pnpm-lock.yaml pnpm-lock.yaml

RUN pnpm install 

COPY . .

RUN pnpx prisma generate 
RUN pnpm run build 

CMD [ "pnpm" , "run" , "start:migrate" ]