FROM node:20-alpine 

WORKDIR /app

RUN npm install -g pnpm

COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml

RUN pnpm install 

COPY . .

RUN pnpx prisma generate 

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy && pnpm run dev"]
