FROM node:20-alpine 

WORKDIR /app

RUN npm install -g pnpm

COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml

RUN pnpm install 

COPY . .

RUN pnpx prisma generate 

EXPOSE 3001

CMD ["pnpm" , "run" , "start:migrate"]
## this will migrate , build the ts file and run the dist/js file 
